(TK-475) Pull in rbac client
puppetlabs/trapperkeeper-authorization pull request #59
Opened 2018-12-05 22:15 UTC by Magisus

This commit pulls in the rbac client library as a dependency of the new
feature to support checking rbac permissions as part of tk-auth rules.

2018-12-05 23:15 UTC, pcarlisle commented on project.clj
> +                 [puppetlabs/rbac-client]
i'd probably just bump parent here and leave this part until it's used

2018-12-05 23:18 UTC, pcarlisle commented
This breaks the repl in the example ring app, which was relying on the fact that some dependency used to pull in `org.clojure/tools.namespace` and now it no longer does. This needs to be added as an explicit dependency for the `:dev` profile.

2018-12-05 23:19 UTC, pcarlisle requested changes
see comment

2018-12-06 00:26 UTC, Magisus commented
Updated. I verified that the repl can now start correctly.

2018-12-06 18:31 UTC, merged